[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# API redirects
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA fallback - serve index.html for all routes not caught above
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PWA service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# PWA manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=86400"

# Static assets caching
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
